const PDFDocument = require('pdfkit');
const Candidate = require('../models/Candidate');
const Job = require('../models/Job');
const Interview = require('../models/Interview');

exports.exportCandidatePDF = async (req, res) => {
  try {
    const { candidateId } = req.params;

    const candidate = await Candidate.findById(candidateId);
    if (!candidate) {
      return res.status(404).json({ success: false, error: 'Candidate not found' });
    }

    // Fetch related data if available
    const interviews = await Interview.find({ candidate: candidateId }).sort('-startTime');
    
    // Create PDF
    const doc = new PDFDocument({ margin: 50 });

    // Set response headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=Report_${candidate.name.replace(/\s+/g, '_')}.pdf`);

    doc.pipe(res);

    // --- Header ---
    doc.fillColor('#3b1e8a').fontSize(24).text('TalentNode Candidate Report', { align: 'center' });
    doc.moveDown();
    doc.strokeColor('#3b1e8a').lineWidth(2).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // --- Candidate Basic Info ---
    doc.fillColor('#000').fontSize(18).text(candidate.name, { underline: true });
    doc.fontSize(12).text(`Email: ${candidate.email || 'N/A'}`);
    doc.text(`Phone: ${candidate.phone || 'N/A'}`);
    doc.text(`Location: ${candidate.location || 'N/A'}`);
    doc.moveDown();

    // --- AI Scoring Summary ---
    doc.rect(50, doc.y, 500, 80).fill('#f8faff');
    doc.fillColor('#3b1e8a').fontSize(14).text('AI Match Score & Insights', 60, doc.y + 10);
    doc.fillColor('#000').fontSize(22).text(`${candidate.parsedResume?.score || 0}%`, 450, doc.y - 15);
    doc.fontSize(10).fillColor('#666').text('High Confidence Match', 430, doc.y + 10);
    
    doc.moveDown(2);
    doc.fillColor('#000').fontSize(12).text(`Summary: ${candidate.summary || candidate.parsedResume?.summary || 'No summary available.'}`, { width: 480 });
    doc.moveDown();

    // --- Skills & Experience ---
    doc.fontSize(14).fillColor('#3b1e8a').text('Top Skills', { underline: true });
    doc.fontSize(11).fillColor('#000').text(candidate.skills?.join(', ') || 'None listed');
    doc.moveDown();

    doc.fontSize(14).fillColor('#3b1e8a').text('Professional Experience', { underline: true });
    const timeline = candidate.experienceTimeline || candidate.parsedResume?.experienceTimeline || [];
    timeline.forEach(exp => {
      doc.fontSize(12).fillColor('#000').text(`${exp.role} at ${exp.company}`, { bold: true });
      doc.fontSize(10).fillColor('#666').text(exp.duration);
      doc.fontSize(10).fillColor('#333').text(exp.description, { width: 480 });
      doc.moveDown(0.5);
    });
    doc.moveDown();

    // --- Interview Details (if available) ---
    if (interviews.length > 0) {
      doc.fontSize(14).fillColor('#3b1e8a').text('Interview History & Questions', { underline: true });
      interviews.forEach(int => {
        doc.fontSize(12).fillColor('#000').text(`${int.status.toUpperCase()} - ${new Date(int.startTime).toLocaleDateString()}`);
        if (int.description) {
            doc.fontSize(10).fillColor('#444').text(`Notes: ${int.description}`, { width: 480 });
        }
      });
      doc.moveDown();
    }

    // --- Footer ---
    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc.fillColor('#999').fontSize(8).text(
        `Generated by TalentNode AI • Page ${i + 1} of ${pageCount}`,
        50,
        doc.page.height - 40,
        { align: 'center' }
      );
    }

    doc.end();
  } catch (error) {
    console.error('PDF Generation Error:', error);
    res.status(500).json({ success: false, error: 'Failed to generate PDF' });
  }
};
